### PR TITLE
Update algorithms

### PR DESCRIPTION
**Pull request by roshavagarga**
Updated algorithms/error diffusion dithers, per PR [here](https://github.com/alexharris/RgbQuant.js/pull/1).

### CODE REVIEW

**Comment by roshavagarga** [comment]
@alexharris Would it be possible to add hyphens to the names here, or do they need to be exactly like the ones in the kernel? Asking because I'd prefer to add the proper dashes/hyphens where needed, but not sure how to do that properly.

**Comment by alexharris** [comment]
Hi, yeah they need to match the kernels exactly as they appear in RGBQuant. But depending on how unwieldy they are, we can potentially display them in the dropdown that shows up on the front end?

**Review by alexharris — APPROVED** [review]

**Comment by roshavagarga** [comment]
@alexharris I think we can leave them as-is, seems a bit too much hassle for a few hyphens/en dashes.

**Comment by alexharris** [comment]
ok sounds good. btw I just finished pushing all of the changes to live, the new kernels seem to be working well! thank you!

**Pull request merged**
